version: '3.3'

services:
  db:
   container_name: nest-postgres
   image: postgres:14.3
   restart: always
   ports:
     - 5432:5432
   environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
   volumes:
     - ./nest-postgres-data:/var/lib/postgresql/data